<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>ink.icoding</groupId>
        <artifactId>smart-mvc</artifactId>
        <version>1.0.0</version><!--version-->
    </parent>

    <groupId>ink.icoding.mvc</groupId>
    <artifactId>core</artifactId>
    <packaging>jar</packaging>

    <name>Smart MVC Core</name>
    <description>Core module for Smart MVC.</description>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>
</project>
